### ISSUE TITLE
question of updated data

### ISSUE THREAD

**Issue by aalgrou** [homebeaver/bankdata#1]
do you have updated version of this data ?

**Comment by homebeaver** [comment]
the last update was Sep 17, 2021

To update use [iban.com-API](https://github.com/klst-de/iban.com-API) - You need a key to use it.

**Comment by aalgrou** [comment]
unfortunately I don't have a key, can you update the data !
some countries not included like jordan, do you have them in version 2021 ?

**Comment by homebeaver** [comment]
Sorry, I have no key anymore. 

Regards
